language: python
python:
  - "3.6"
dist: xenial
before_install:
  - cd /home/travis/build/ucgmsim/
  - git clone https://github.com/ucgmsim/qcore.git

install:
  - cd /home/travis/build/ucgmsim/Pre-processing
  - pip install -r requirements.txt
  - cd /home/travis/build/ucgmsim/
  - pip install --no-deps ./qcore/

script:
  - cd /home/travis/build/ucgmsim/Pre-processing
  - pytest --black --ignore=geoNet --ignore=NonUniformGrid --ignore=RegionalSeismicityTectonics --ignore=SrfGen/NHM/deprecated --ignore=test
# TESTS need to be rewritten
#  - cd test
#  - pytest

